const input = [
    "jNNBMTNzvTqhQLhQLMQL",
    "VCwnVRCGHHJTdsLtrdhrGdsq",
    "wFJZTbRcnJCbpwpFccZCBfBvPzfpgfgzzWvjSzNP",
    "wDWgDfWNTvwvgFfWfddGldJVprrrVdNlrN",
    "nLnmLSnmMVJvSrHqdV",
    "MsmsbLvtzMjFsCPDsfBwwT",
    "WTqSCqWSWqSgVZqJHpHmHrhMMVrRhBnn",
    "PtLGLGddGGMCpprM",
    "jFvLPPlLjvfjjffsclvPqzzJWTbqNSWZsbSTDzCW",
    "lLSSrfmddlNpnmLdfSPddDdbZQTZgZjbZgjcQZHQPjQgZP",
    "MJMnhzBJVJwvGsMRhRhTsHTjZjHFctbtHZcgZj",
    "vzvBWGJMVGwWGGhGqVBnGzVGDfCDmrqNfrrLSdpSfLSpNmNC",
    "qGWLgfbWhqpLgZbJvTRWJTvMWRslMv",
    "FQwPwNPCVFQQdNcFHNcwwsvslRDRTMDMsVTGJGtRTs",
    "wQHnwnQFPNPdjnnPjhphGqBrfpBBBfZf",
    "mpVpmtPhVtPBLLbQTJpBLZ",
    "vzFMlMzvvRZMTbJQJQbf",
    "srqzvRRqdvzFFrDnvqldFVtwCVCHWNqJHNNcHchCPt",
    "CQJJLZCJLqNMMDDgGLVV",
    "RfRFFszTtzbWTFnRtFrRrWvNHghvBVGgMffvmBVDNgGV",
    "znsjWzstnWjbDnDbTZCpwZcjpjZqQCwSPp",
    "jRrzzrPjLnnpQQDsjj",
    "CTVnTlZWHTcqZBcTTTHqWscQsQDQQDsmmQfvfhwDmv",
    "qlWFWWHTZTlqTFWZHtBVFdlTGdNzRnNngbbSrrSNNzPgPGSz",
    "cWjbcjnssMmRPWbGsWcMbfLBFrZBBLLgZwBrlfLQZtCw",
    "vqpvFHNvhvJzdZQZtlgNNwlrrw",
    "JzqVVVVpzhVJqzhSzJhhDVnFjRRMsPnSRcGMRMjWjWmR",
    "NznNGQgSRQffbbsR",
    "jjjCLwdvLcrhqdblFJsFSPfbDP",
    "qrrvwHqjtLmSSggpBtgn",
    "LGPtFtTfTfTfLrrWTSWGPrrsszbsjZHzgdzSwzbHdsglwl",
    "NhHpVpqNNqbdszRRRb",
    "ccBMJVDNCvvhDNpvNDpnNCVCHFPTmfLTGPMQrfLGmMLWWQQL",
    "dRgRhVLRlncZSSrtLp",
    "WJmwvvvjQvWwFBBvFJPHpwvGWTScGsrZtttGTSsrzTsSZt",
    "FFHJjmjjjPMvfHfwpdRqMppghdRCddDg",
    "NDTRFSnNsVVBDVlM",
    "JjLZWqwjHvfrvmHHvjLWWLlhPlnPlChlQhJQnnzPPBCV",
    "mwHvHmpvwpLmjnvpvLvvNGcTTggRbdTGcbNbTTpS",
    "GGhZQMsmGRfMwfpclgdBlbblBBZgJc",
    "tFvFSTSDnDTTLtcFMbWcBgclJrgd",
    "vzDtzMVtnLTTMTSjSDHtppqhsqqfGjmpPhmsRGPG",
    "MfJtWTTMJfzBbVWPZWQbNnDV",
    "FvlgSHSLvmCvZjgcCQQsPQQsjnbVDNVsdn",
    "HLhclRlHRmHvmLmclLZFSFwRRRpJMtwJwfGGrrtrwfpf",
    "scsswLQcGmQmNHCqvrsHqfff",
    "bdnPSMMMClbBBPCdDDnDVMDWWWvfvWFfFJfNqqNVFqFNfr",
    "bDPTlSTPPbSPjnPSbGmQLCcjLjwzRLcmCG",
    "tFFJjMnFhdcMMJlWtdnlFczBSZGNSjGGbBGZLbZZbLGB",
    "QRgqwwvsLssZnGCz",
    "gqfvvnpfHwRmHTFdFcPdJJmJJc",
    "fccTzVVcfSmdThTTFJPFgg",
    "wLsWfppsjBrnnwjCBZnZqJJQGhBdFJddQhFqdQBG",
    "pZrNCWLwLZLjwwWMftmNzttDcVzVvt",
    "rZnVVjVSMcrwsNbc",
    "dLvQLBLFddvBLzpGmddQCqNswzsMjbhgbblbcwshlb",
    "LLCCWjGBFPmCWdmmPWLdWBpLRZDSPRnHSStRfnZnZTnSSTfJ",
    "ddfnQRbpldRlRLgFglqGCLqsGq",
    "BWBVDZWTBTDPvVTZVDBDNMbhcLLHsFqgvHJsLCJCGcHGsJLH",
    "NPZPDMWZMbZrBVMDDWNmBhMVpSSRpzjjfjpwRnSpwzRzdzjr",
    "bvPSBttgGmZwScwShS",
    "NJspjJLdprzHgjrLzLNrnHQCmmcZQWlcQcNQwlwcQCZC",
    "HdRJsJrdHTbqGMDtgDqT",
    "sNVvSdTstDCtdzdzSCwTzCRhRQjfclMflppjGhffjZcN",
    "rgWlrnLLbqbQMfMphpWjjf",
    "BmrnrFPnnBLlqVwDCtCtVPDTzT",
    "mJMqlVlttQlFVmzFQMQMbQMSSDNwwdSddNddwdDswRDVdR",
    "GGZgcfjrvCCZvgCZqvPHSwRBBsBwswcwBNTDTcSR",
    "GZppfGHGrgGprZhLthFJhFqLWWFhtq",
    "WDHHLtRBHgDnVrWFVFBTdzzZLLjZzjjvddLsvv",
    "JlqmMpCMCGMwbwZddTtCtv",
    "cJJqSplpfSGccJGthFVcVHgFBWBgHgDB",
    "tlFwbWtQFLJhlBFlWPbwmsQndTrrqdnggjqdgnTgTT",
    "GCMBDDCvRpDVpRpHrsgdqTjqgdHcsjHd",
    "MDDvCVGzBGfpzBSNMSRRmwbLWlPmzbPmlJlWbFbJ",
    "fzFzFHBfnvpHFbnzbHfBHZggCGgtZCltDGggdCCVtZVD",
    "sLMNSccQLMSrmLcshLvtCGllPtDdGgtJgmlV",
    "cwLMwwNhQhsWSjqTqHnHbjWTvH",
    "NWlqqhNNnGtNvvWQdrVGBBQdVrwRQr",
    "mppCjppMrDTSgDppCDTMQVRwdBbBQVVbQdQsVB",
    "pgzzTFFFrjHqHnqJFWnh",
    "ncQrhQjqjVQhGsGBbhtsstTp",
    "RllWFLRfZrGlBTbg",
    "vFLLmfNRFSNDfSNjcwqJVrVVzQjc",
    "mmGrgwmGDGcVWVjNNW",
    "nDsqfPCHnpntDssfJPDPjWWhjNTTcjjhTTNcqWcc",
    "DfPCJLpbldRrlrdwmw",
    "dJDNbRhNbJdhqCnrWjhsTWvplg",
    "LMHrttLFcMmcMFLmtGplCggpjjnvTpgnTTFT",
    "czZMzrzVZzHZdNdbDDqDVQNR",
    "sbsJgbsmzdgRgWdg",
    "LLLFBzGMLjzzFtVFwwwCPPRCCqQQTnnCMMCMCC",
    "GllfptwjLjlGFVFjGzpFFNbJDmprrNDsDmDvJhmcvp",
    "SccPbfbncpcfsjbRjMBCTTFGMTCQtJtzFFFJ",
    "vvvdgVhlmlwlgZLgmJhWQCWGGbWtWJhzTJ",
    "NbLNDdbLVmqqmfcsrHcrpPqrcH",
    "HcgDBJSHTCzjjnMNJjrW",
    "VppGMwFwllwwbZZrjvnqmzmnzpqjNv",
    "wZlhtPGPLFVFlGZbVtVTQLLBQRRTSHTSMDCgLs",
    "HPMMnhBHlMnMBPBHJHPWfdnBmjvLZvjTvZTZDgTgTmQmZhZZ",
    "SrzrSScrctrwVzCSCmzQjmLTLvGDvTjGbm",
    "CswstFRNpcwVNRrVVSVwpwpHJnnWWBBHfWHlffWfQMnM",
    "mlFMtqjvMdqjmMCCJZsRQBnszlZz",
    "HcNgcPLcHLwtcfZBTsnsHJBJTzCQ",
    "LGGNhbNtNLDfcgcwfbgthfwFrqqVdFMqMMhMmvShFqmvVv",
    "NbvbBGNvhNhnhpbgpGfBvNgmRjCdPCPCCRCQmmpRdTmTPR",
    "qqFSSqWrtSSccjMdQMHFMBjPMj",
    "SBDSBZZZwGGZNJJg",
    "qTdHSLSFRZRHHZVgpzhbJszchsnsLg",
    "tDvflvrGttDCjlQfmCGvtCftczhbzwJczcJgznNmzJNhwgsp",
    "tQlDCDtrfrtlGrjlQBHFHPVHbBbZqTZdVZBF",
    "MTwvsQJMvvHwVMMJMQNNJRPWWjCllrlWGFlSFCpjgFVSWr",
    "zhcmnRZmqmWjCSFrFqCW",
    "ZbmhZcdZznZfndtwDtMMsRQTTQNRQw",
    "ZhhVqQTvZvVhSmQZcClRCLPCgTGGLbgl",
    "dJWHwndMHswswlGbCmclmLHbbP",
    "dnwwNJnjBjwwdddnjndfWvmvSNZQNrVVmZvZFvvQQv",
    "trlrlrZzsjRjdFhlpwdpnpdp",
    "QqLvvLQmLfQTLbLTfHmqHHLqQgFBdCJBBgggCJdhgJwCggBF",
    "DPDvqLqffqfhSVjVPSPtsj",
    "gsnVdcBcjMMntGMh",
    "RQZLRZlZDRJDCzCjblJSDjQZWWTWPCThMTFGNPTNttGwCFMh",
    "pDlQbSlzpQsjVpjHVfgs",
    "zgqtCtJltdGttJgVGPPJCtJvQFsFFbTFssNDNDsHLbTQbssP",
    "rRcwBnnpcmBqpbLHDspTbFsb",
    "mwRqrqrmWrZnfWmBmnRZlgClgJCJlGJzClGMtG",
    "jlzHllmPnpHlHZBWZJJDWMBNVH",
    "bQrhDbcLgsQrtdVCJWfCCBMMVWrJ",
    "QhGdGcLGwwwtcDzznppPpPwlpnSS",
    "qbpqvWFHbFHHsWwPqPpsVWZTlDcLDddddDrmrcVZDrmT",
    "MCgSSJMCztdmcLzlrlDl",
    "QCRMRSnNtRSqqRjsjLPPvp",
    "ZnZrTfsWWvhVSRmzqqnn",
    "pLGBLBgLCpgGpbdLbgMClJTmmhShSRShqSBDQSRRmQVV",
    "dpJPldgMMbglFdrNWWjHZNccTjZP",
    "CCZCQzwwdmMGDWMmhCMJgpnrnwsTrFNLgnpNgg",
    "jfStHtcjqDPbPtvqvgLNpppnHsrsFgnFNp",
    "fcqqPPPtPSfRVBBRPRPbvQzzhQWGZQVQQZDQMMzGQM",
    "VVlDNDgppgtNltlrJPbjSzPPzjsMsjBBMWMM",
    "LmGRmfmwCqQqbsQBMqJj",
    "cHRcCFfmfmGLJLGFcJLFwfdlhDgptthhHpVrNVdhlvhl",
    "vSSdnBVpscwZcBZB",
    "mLHzqtGtNfGHHFNHMhJMthsbcJtctZTw",
    "GHqHHGzNDNFCfqllCFqVDdPSDQnddvcpPQjdjg",
    "CMWcwGTrvzDWzrDccDCGzTTTplZgSjggjSpSljSjBpSmgmWB",
    "nssRttdsnhsdbFhtVFhNpgwNpBBgHHBBBBZSjNSl",
    "PnVPVPLFtvPvTwwrQq",
    "tlQlqlJCCJWgFrprPjpGVpQzvp",
    "SDbwShHbBZZbhcBdDBDSTrsVpPrzzzHVzNllzGlVNv",
    "BTbbScwRhwZLnLtfJFLFJgWl",
    "VDfPVHfDVMMfHSPSMTVfqgFthFcFrtcdhrhDQdDmdcdt",
    "bWGGHCplWnJNpJCCnlnNwdcwQhmmdmtwddBNcc",
    "HpGCnZGllzlzJWjnCbbnCnRvfvsSTVVSgVLqSsLsLzPPLV",
    "fQqcfqfSDzDWffDZ",
    "NcCLCtPCPMtNBwdthpLhPwzsHrszsZssTsWrDrDVTNNH",
    "twMPBtCpLBCtwMPpJcMBSjjnngqSjQQJbQjjmgmn",
    "vQwVQQVqcJvVJvCpQBCLpdgSFCdjjWWnMSgnSjgjbj",
    "hszPRDTVDWWWRnjWWj",
    "TtDDZsszlPllhPzmPVGssTPpQLcpvpBpZpcfpvrvQvBQLv",
    "sRmGqqzzzgCtRrttCP",
    "cffSwNDddTdfGWtgNCrtGMPP",
    "GGcTwHwHvjqLLjLvlJ",
    "JSdjLJMBdMSrfwwLpWgzWmvDhggzWvfmgD",
    "VsRtVllstHHNllsQsHQRzchcnDmvmvnRvvvcnZ",
    "tGVGCTTTtTFVbsTTNTHsTTqBqBLrBCjqBwqJwqBzLqzw",
    "MhjTJjlSDrplQvFQ",
    "RHttqbNGGmbbLmLmdqbgnFQwrZswQrwDpFpppdwfvQ",
    "gCNmDHHRCLHnWWSCjhWPShPz",
    "BvzpbBwBmsDrmGVgZFDm",
    "TnNRdtlRlCdFFGTLffrrGf",
    "jltNtRCPSlPNtcpwpGzjMBpvbhps",
    "hflJphNDmmbpfnfplbcvLsHVLsrsZsVvCb",
    "FgTFWqTBfFPfFqQqTwHsHccVVLQCZZZCVH",
    "BSSRTGWBgFggBWgBGStTGpzNztmjjzhhzDfNnMjnph",
    "mDDFjjFmVlTZJttffD",
    "hhRvNNCvdNMRLzhSzpptwslNTfNQntsJQZZTlN",
    "WCdMzdMzhMdvRvLhCRLPvjgHmggmbmbblgWcGmcbcG",
    "cScMdhsDhDDdvGzZptzGcnGtpB",
    "NPWjJqrjJWwrSFWRJlrlNWJLtZznLBBzZznLqnpqnpnznV",
    "NWNQwNPjCSQTQhTd",
    "fVVCVccppZMZMMCBzJTNJHWZTWZzNF",
    "QrmmPhDqPhsPRhrlbgRDbbPDJNJTnJzmzzfNNTNHNJNWmnvF",
    "DgbPLbPsQsrbsqLbgllsQQptfwSjwtVLfwdcpCjVwwSp",
    "ZlsmlrZZJcQmhBhlNrsrJRRbRCRggRbzGCRHgRCDGB",
    "fMFvdfVTTdjWTTTfvSjVjpjzcCbFHGPHPDbPHRCFGGRHHG",
    "cdvfSWjfjpdVqSwSvMdLrlrmhqZhhrrLLJQhNr",
    "sWVVmDJsNWNjcSNJZcNcZWWsHTGHTChhHGtHsFFbbsfHhH",
    "nqPRwQRgpQRPQQgMQgQLQqBhvTRtfdfvfCbFtTFFFTtvff",
    "qgrPMLLPpVlbDrVrWD",
    "VcGjcCHcVHPrGnjQDQgDgQDFtdglRtlQ",
    "bWWhfzJhvZWJzNpmRTtsDLDgRTsNddFT",
    "MhJMhJbMmSZbJZwSCtjqcGrrnGjC",
    "FCvpgDsZNsCbvvvpVwcDrjcrmVMwVwHJ",
    "fhfWdPhhhhRQQqzdLSRHRHJjBTTmcrTMrMrwmczcwwTz",
    "qndhdQWndftfhWStfLQQfWgFNsgFpHCtgCNbGZZlZCll",
    "mqTCNhTNmGTLwLNfLrSrgZHDvfPDPv",
    "cjsMQppsFnFslnRQQGMDHGZHSgzHPDZDSf",
    "stWFjcFFsJlQcQtwtbVwCmCthmBTGb",
    "fmsffcqhmqPsnTCnCcQpzjSSNpBWBTQpVSSD",
    "vHbgLRvvvzdgjVVjWg",
    "WltLWvWlqcChrhlf",
    "CtwjffWrdznRtzCwLsmGLlLMsMmMGb",
    "cZFFbgPgJZDchMMPVsmlPGmG",
    "SpNFJBJccNgDcTJJTdbStbnntrCdSrjWnb",
    "qWzgNFqzqHNTBzFNCZCGPpPlHmdPblls",
    "rfSJRJnhhnJDjrfvRStCmpdGsdlDpZZZPbPCmW",
    "cffRvfnnVRjFTWVTLQMFWN",
    "VcHhVrVCQQWhffzcRZznnZFf",
    "dDSCGSsSblwDdmLqvnFZzNZplfpfRZfBnl",
    "tCCwGmSqbqtwsVPjVJWtJHHhQV",
    "fvvTcWzGcCJrJGJvvHMbZTmRQTbpMdQQsR",
    "SgFhVgllLgjLgwlwljFqVFSFdjmBHmZdRMdZpbjpmpjBsHdM",
    "LNqFnlDgVqllwLFLnVSgLFZtCzzzzvCGGccCCDCfvJrv",
    "FczpzmSjVVpSQrzzcRpRcrwqMtJqwtvtLHvQwtLtnJMw",
    "TvbGGbNfGCBBLHtJBHDZDMqD",
    "shgdNTGgvNsflspcPjzVdmppczrV",
    "JHLPLTsSllgSSPPSPLTRTdjCZGZDGGgCdqZtZCZdZt",
    "mhFpnpFwqdGbdFDt",
    "prpWcvnmhmpccBBJMJJlPWLHMDSDWW",
    "GcMcjDbDMMjqHBHVlHvv",
    "rLCrwNJCnwrZNLWQQwzQpRqQPlBRVVBRvvtHqf",
    "zhnrnzdrCwLJCwzwCMGcbdFTscTmgcFlgc",
    "cnwlFrdMsggblgsrMbncwrsWzjGBTjznBzWNzPzTzfjTzf",
    "vvVVHSpQvvRQDJGGLWGfTLTBLQMN",
    "hCmJqVvMSpqqChCJHDZrFsdhrtgFhttZZhts",
    "sfDNqLNpqpzCzLsDqzbCVWRhjTNhShTjHmmjjhStBmvT",
    "wZrlwJwFJGlFMTjhBBZTSTRSbv",
    "wrQrgnPwMsnLbfffVc",
    "hDcwwGWhMMssTcdM",
    "NQmLbNSZHQSHSNpbvfdqfRsZMqssjqdd",
    "LNVtLSSHLSgLNrgwJgJGnBwFMBzD",
    "CRDfCbfjcnRCBVfjVMfMjZpPptplPWtppStpSlBqlq",
    "HdTFLGsdLrzNWtvqPTcpgPZl",
    "JLGmmHrwJGwhjmfMcbDjQC",
    "VShGpPbWjcPCcTLcPN",
    "HqfqDfDFFJDvZRJvqZRRqHZdNcwjllwvQQLQlllccwclCMCT",
    "FddsFmJjjrgGmbSSpS",
    "NRFFLtFtqFLGsdnGbQSs",
    "ljMfMBDlJHgBVHgVflfnwdsSQQbddsSsqnqGfs",
    "PlzDzjljzqRzWzZW",
    "dtzZZbctPzwdlzRwlcdfRgtQJmFmhPSmmSsQQFhsmqSFvm",
    "nDjHnNjjjMnfjNTMWhHQWJSqSSQmhqhm",
    "CDpVCfrjLnnfwtBcpdcbcBZt",
    "sssZSZtDfHbbdtBTCRBzRDFJCBLp",
    "jwWgmWlNQNLlcjWhgQlrQQWrCCJJzFCMVMTzpBMMCVCMTwpT",
    "ggLgrqljLlGvHqttftbP",
    "cSGBFsFcSRZSQGsgBNgVMwMhDQDVfqPjMhwwVq",
    "vnCTLlrpPlHzzjbMfqpbww",
    "rJCnlmClvWvLrTmtTlZcZWSSWPGGdNcFGgcR",
    "lfDDvZZSvLtDtCQZltCqVBWVBCbHJjRdNqWq",
    "pGGhhzMRcqMBqMdVBN",
    "mzgwGrrwhThFGPmGPcFGpwStTfltfDftStDsQRsflDQl",
    "LjnSjLZLBcbBdDqzND",
    "rrfhfMRmpsghfrhGhgQrcPNtZcqNCqdCqPzcNZMM",
    "ZTTgvRpmfffpfgRRhWnVSJJLLWnvJHFlFH",
    "lstcGcttdczzsWVCvQVLCHHnQHWL",
    "rjmJrmfmJMqvQTLvqfGG",
    "JbNrjGjGrMDRJghZggcchhDhzc",
    "tftJQwCgSjpdWHjbRJ",
    "DcwvlZBmGvHjdbczcRpb",
    "sqwDlsBvGNSMQTCNfCTC",
    "DwDrtvMHtBCvcpDcjCMFtBCblJfJGJbZlfzrRlJdbRdZld",
    "sPLPmqhSnLQQSWqlbzRRhfJCJfNJhZ",
    "mVCnWCsQqqLTPWmnDVMFVtHFtMBFpjwM",
    "scChGddJztdNswNsdDsthvmpVmRVcZjmvVvRSMZVSZ",
    "lQLCWgWHCWbFPbbbHqLnLPHHVMpVRgSMmZVSBZBjZVSjRBZp",
    "QrTlTHbPnTsJGtsDdGCr",
    "fMjgFqtFWMhtjcNQSDMmNlCCDMQN",
    "sVHdHdJHwPGPGwwbpJGTbGTvClldmvRSnvlDlLLSlvRnQl",
    "pJbHPHJGVbBswpTcfrBtrhmtrFczzq",
    "SDGSDGVPqqqQPGrTQVTQDrSrJfHJgqhgJqzhJJmWfHpWpzmg",
    "twCdCWMLwbtLLjBddgfcJgRHfRRpfcpRHM",
    "FZdbvFFbVvsWsQsW",
    "rzrRgqGrwgjRVqJCHLzCCWhtDbCC",
    "dTZnNpvBvnJdBpBnsJPvsSCbthLtLbbQShQQLHtSST",
    "BlplPmdlFsslfJmmRfwfwMjw",
    "PPHSrmfHTnmHnHBzRhbFgfbFwzQg",
    "LcsVsGtVLtLqpzwBvgzQRgTTTp",
    "TjLJGTTJWJZZWWZS",
    "tHcshJcJRhLsQscVtccJLRHfvlPjZFSvmvSbvfLFfFFbGZ",
    "drwdTNlwwBTpCdCdwGPrrmjjmjmbSjFPrF",
    "wglnzCDpJtQcztMR",
    "bbMjTbBvgjZNSqldTlVt",
    "wwrcFwsrsnnCQzrCsLnRsQZcNlpJVZHdttZVttSZqJZd",
    "GwLnrsmFCCzqzhvPbPmWmvvfjj",
    "dcnwQdcdrJdSwSFBBqfBfwMqfBfzsh",
    "RgmZpWlCClRlTgBZbhHJJsZjfBHZ",
    "DlNVWgWpgDCCNRDJFcrtQGrrVnrcFPtc",
    "sWSHsdSrHWHsbdsddBsbjmfwffmJDJwcfDQgfvwJDj",
    "ZNGPhRqCCRNGNwSDvmmwwgDhgf",
    "lGlTLTGTSVVFqVTqsFHWntbWBsBsnBHb",
    "QRRgRvDwWDVjmSbDnbTDlDnbqS",
    "rHCPPHrcLFJcllqbTlpq",
    "CldFrNFsgVhhhWgN",
    "qSfMgNqfpmSmlQrRFG",
    "cbBczbtbZTcPWzcrTrmRrLGFTQQFmJ",
    "PBZChtzzcWPcZtBvPjtzBBCfHMMNdDgDpMfVfVpHMqNR",
    "LJPPCHtgtLDfFfvTLwfv",
    "pVGWGGjjjplhpGGVjWnldsvrrMFvfDMTWBdFrfFF",
    "cjlhShjchhjGGmNVjplcQgmTPtHPPJmQgQHgtqgZ",
];

const isLower = (char) => char === char.toLowerCase();

const getScore = (char) => {
    const l = isLower(char);
    const val = char.charCodeAt(0);
    return (l * (val - 96)) + (!l * (val - 38));

};

const split = (str) => [str.slice(0, str.length / 2), str.slice(str.length / 2)];

(() => {
    // Part 1
    let totalScore = 0;
    for (let i in input) {
        let bag = input[i];

        let [comp1, comp2] = split(bag);

        for (let n in comp1) {
            let ch = comp1[n];
            if (comp2.includes(ch)) {
                totalScore += getScore(ch);
                break;
            }

        }
    }
    console.log("Part 1: ", totalScore);



    // Part 2
    totalScore = 0;
    for (let i = 0; i < input.length; i += 3) {

        for (let n in input[i]) {

            let ch = input[i][n];

            if (input[i + 1].includes(ch) && input[i + 2].includes(ch)) {
                totalScore += getScore(ch);
                break;
            }

        }

    }
    console.log("Part 2: ", totalScore);

})();